version: '3'
services:
  driver-booklet:
    build:
      context: /home/hxn/projects/driver-booklet
    image: driver-booklet
    container_name: driver-booklet
    ports:
      - "9999:9999"
    restart: unless-stopped
    