[project]
name = "driver-booklet"
version = "1.0.0"
dependencies = [
    "python-dotenv",
    "flask",
    "flask-login",
    "flask-bcrypt",
    "sqlalchemy",
    "pywebpush",
    "Flask-APScheduler",
    "psycopg2-binary",
    "Flask-Mail",
    "flask-admin",
    "flask-babel",
    "xhtml2pdf[renderpm]",
    "geopy",
]

[tool.uv]
# Ignorar qualquer tentativa de instalar pycairo
exclude = ["pycairo"]

[tool.uv.sources]
# Forçar reportlab sem cairo
reportlab = { version = ">=4.0.0", features = ["renderpm"] }

[[tool.uv.overrides]]
name = "pycairo"
version = "0.0.0"
# Isso impede que pycairo seja instalado